Repository PKU-Alignment/safety-gymnasium, pull requests merged in 2023-04, with the labels that each got.

#35 feat: add `ruff` and `codespell` integration
  .github/workflows/ci.yml
  .gitignore
  .pre-commit-config.yaml
  Makefile
  docs/conf.py
  docs/index.rst
  examples/env.py
  examples/vision_env.py
  pyproject.toml
  safety_gymnasium/agents/ant.py
  safety_gymnasium/agents/car.py
  safety_gymnasium/agents/point.py
  safety_gymnasium/agents/racecar.py
  safety_gymnasium/assets/free_geoms/push_box.py
  safety_gymnasium/assets/free_geoms/vases.py
  safety_gymnasium/assets/geoms/apples.py
  safety_gymnasium/assets/geoms/buttons.py
  safety_gymnasium/assets/geoms/circle.py
  safety_gymnasium/assets/geoms/goal.py
  safety_gymnasium/assets/geoms/hazards.py
  safety_gymnasium/assets/geoms/oranges.py
  safety_gymnasium/assets/geoms/pillars.py
  safety_gymnasium/assets/geoms/sigwalls.py
  safety_gymnasium/assets/mocaps/gremlins.py
  safety_gymnasium/assets/robot.py
  safety_gymnasium/bases/base_agent.py
  safety_gymnasium/bases/base_task.py
  safety_gymnasium/bases/underlying.py
  safety_gymnasium/builder.py
  safety_gymnasium/tasks/button/button_level0.py
  safety_gymnasium/tasks/button/button_level1.py
  safety_gymnasium/tasks/button/button_level2.py
  safety_gymnasium/tasks/circle/circle_level0.py
  safety_gymnasium/tasks/circle/circle_level1.py
  safety_gymnasium/tasks/circle/circle_level2.py
  safety_gymnasium/tasks/goal/goal_level0.py
  safety_gymnasium/tasks/goal/goal_level1.py
  safety_gymnasium/tasks/goal/goal_level2.py
  safety_gymnasium/tasks/push/push_level0.py
  safety_gymnasium/tasks/push/push_level1.py
  safety_gymnasium/tasks/push/push_level2.py
  safety_gymnasium/tasks/run/run.py
  safety_gymnasium/tasks/safety_velocity/safety_ant_velocity.py
  safety_gymnasium/tasks/safety_velocity/safety_half_cheetah_velocity.py
  safety_gymnasium/tasks/safety_velocity/safety_hopper_velocity.py
  safety_gymnasium/tasks/safety_velocity/safety_humanoid_velocity.py
  safety_gymnasium/tasks/safety_velocity/safety_swimmer_velocity.py
  safety_gymnasium/tasks/safety_velocity/safety_walker2d_velocity.py
  safety_gymnasium/utils/keyboard_viewer.py
  safety_gymnasium/utils/passive_env_checker.py
  safety_gymnasium/utils/random_generator.py
  safety_gymnasium/utils/registration.py
  safety_gymnasium/utils/task_utils.py
  safety_gymnasium/vector/__init__.py
  safety_gymnasium/vector/async_vector_env.py
  safety_gymnasium/vector/sync_vector_env.py
  safety_gymnasium/vector/utils/tile_images.py
  safety_gymnasium/world.py
  tests/test_env.py
  tests/test_vision_env.py
Labels: enhancement

#46 feat: add `Gymnasium` conversion wrappers
  README.md
  docs/conf.py
  docs/index.rst
  docs/introduction/basic_usage.rst
  docs/requirements.txt
  docs/spelling_wordlist.txt
  safety_gymnasium/__init__.py
  safety_gymnasium/bases/base_task.py
  safety_gymnasium/builder.py
  safety_gymnasium/wrappers/__init__.py
  safety_gymnasium/wrappers/gymnasium_conversion.py
  tests/test_gymnasium_env.py
Labels: documentation, enhancement

#16 test: enable tests in ci
  .github/workflows/tests.yml
  safety_gymnasium/__init__.py
  safety_gymnasium/bases/underlying.py
  safety_gymnasium/version.py
  tests/requirements.txt
Labels: enhancement, dependency
